### Get task list
GET https://61fbda4e3f1e34001792c65e.mockapi.io/api/u/15/tasks
Accept: application/json

### Add new task
POST https://61fbda4e3f1e34001792c65e.mockapi.io/api/u/15/tasks
Content-Type: application/json

{
  "name": "This task was added via API",
  "done": false,
  "urgent": false
}

### Update task data
PUT https://61fbda4e3f1e34001792c65e.mockapi.io/api/u/15/tasks/92
Content-Type: application/json

{
  "name": "New task renamed",
  "done": true,
  "urgent": true
}